# Generated by Django 3.1.2 on 2020-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SER_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30, verbose_name='username')),
                ('path', models.CharField(max_length=200, verbose_name='filepath')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
