# Generated by Django 3.1.2 on 2020-11-01 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ser_data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ser_data',
            name='UserName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='ser_data',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='filepath'),
        ),
        migrations.AlterField(
            model_name='ser_data',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
